- app/routes.js
- app/views/ineligible.html
- app/views/teacher-check-answers.html
- app/views/teacher-contact-method.html
- app/views/teacher-employed.html
- app/views/teacher-location.html
- app/views/teacher-payment-method.html
- app/views/teacher-qualified-teach-first-ske.html
- app/views/teacher-qualified.html
- app/views/teacher-reference-number.html
- app/views/teacher-route.html
- app/views/teacher-still-teaching.html
- app/views/teacher-success.html
Created all the pages for the teacher end to end journey
> Adding pages

- app/views/includes/head.html
- app/views/includes/scripts.html
- gulp/copy-assets.js
- gulpfile.js
- package.json
- Add the accessible-awesome-complete JS library via npm install
- Add gulp task to copy files from node_modules to public assets
> Add accessible-awesome-complete library

- app/routes.js
- app/views/teacher-check-answers.html
- app/views/teacher-location.html
- gulp/copy-assets.js
Implements the accessibleAutocomplete JS library to the prototype and integrates it into the 'teacher-location' page so that users can select their school from a dropdown list.
Passes the school selected to the 'check-your-answers' page.
> Implement autocomplete

- app/assets/sass/application.scss
- app/views/index.html
- Recreats the links and content to previous prototypes
- Links to new prototype
> Add content to landing page

- app/views/admin/emails/claim-received.html
because it was supposed to be easier than Juan doing it but it wasn't
> new copy for the admin email with new content design 

- app/routes.js
- app/views/awarded.html
- app/views/check-answers.html
- app/views/consent.html
- app/views/contact-method.html
- app/views/degree.html
- app/views/disciplinary.html
- app/views/eligible-confirmed.html
- app/views/ineligible-agency.html
- app/views/ineligible-awarded.html
- app/views/ineligible-degree.html
- app/views/ineligible-disciplinary.html
- app/views/ineligible-term.html
- app/views/national-insurance-number.html
- app/views/payment-method.html
- app/views/private-agency.html
- app/views/qualified.html
- app/views/reference-number.html
- app/views/school.html
- app/views/start.html
- app/views/subject.html
- app/views/success.html
- app/views/supply-teacher-term.html
- app/views/supply-teacher.html
All the changes for Mark,
- Re-word questions
- Re-order questions
- Change routing
- Amend ineligible pages
- Add in new you are eligible page
> Re order questions 2

- app/views/index.html
- Divided up Alpha and Beta prototypes
- Linked up beta 1 prototype using new heroku app
> update index page to access all prototypes

- app/views/awarded.html
- app/views/check-answers.html
- app/views/consent.html
- app/views/ineligible-agency.html
- app/views/ineligible-awarded.html
- app/views/ineligible-disciplinary.html
- app/views/ineligible-subject.html
- app/views/payment-method.html
- app/views/start.html
- app/views/success.html
Amends off the back of our team run-through on Tuesday.
> Pre ut amends

- app/views/index.html
to include version history for each prototyped sprint
> Changed the index page

- app/routes.js
- app/views/check-answers.html
- app/views/national-insurance-number.html
- app/views/payment-method.html
- app/views/reference-number.html
Change prototype so if you are editing a previously answered question it routes you back to the check answers page.
If you hit and ineligible screen / successfully submit your claim / or load the start page it will set the prototype so you proceed sequentially through the questions.
> Back to confirm

- app/views/check-answers.html
- app/views/payment-method.html
- Fix typo on initial teacher Training
- Reorder sort code and account number inputs on payment method
- Update check answers to reflect new order of inputs
> Fix issues with payment method input length

- app/views/ineligible-agency.html
- app/views/ineligible-awarded.html
- app/views/ineligible-degree.html
- app/views/ineligible-disciplinary.html
- app/views/ineligible-subject.html
- app/views/ineligible-term.html
- app/views/start.html
- app/views/success.html
So a user can check the service guidance, all links have been amended.
> Replace relevant links with service guidance

- app/routes.js
- app/views/awarded.html
- app/views/check-answers.html
- app/views/consent.html
- app/views/degree.html
- app/views/disciplinary.html
- app/views/eligible-confirmed.html
- app/views/ineligible-agency.html
- app/views/ineligible-awarded.html
- app/views/ineligible-degree.html
- app/views/ineligible-disciplinary.html
- app/views/ineligible-subject.html
- app/views/ineligible-term.html
- app/views/national-insurance-number.html
- app/views/payment-method.html
- app/views/private-agency.html
- app/views/qualified.html
- app/views/reference-number.html
- app/views/school.html
- app/views/start.html
- app/views/subject.html
- app/views/success.html
- app/views/supply-teacher-term.html
Patrick has provided the amended copy for lots of the pages which are reflected in this PR. I have also taken a best guess at some of the outstanding ineligible screens based off one that Patrick had amended.
Dependency - please note that this PR is dependant upon #25 being merged in first.
> Copy amends june

- app/views/eligible-confirmed.html
- app/views/repaying-loan.html
- app/views/start.html
- app/views/subject.html
Added in small changes that came from the UR script planning session.
> 302 mps changes from research planning session

- app/views/number-of-courses.html
Fix typo on number of courses page that was identified in UR
> Fix typo on unniversity -> university

- app/views/eligible-confirmed.html
- app/views/start.html
Following on from feedback our content designer suggested amended text
to reduce the amount on a page but provide enough information for users.
> Make information simpler

- app/routes.js
- app/views/capability.html
- app/views/check-answers.html
- app/views/ineligible-capability.html
- app/views/reference-number.html
- app/views/start.html
- app/views/success.html
Content designer recommended splitting the question following some
feedback from user research. Routing changed to accomodate the change,
new question and respective ineligible screen created.
> Split disciplinary and eligibility question in two

- app/views/contact-method.html
- app/views/eligible-confirmed.html
- app/views/private-agency.html
- app/views/school.html
Some questions had margins and others didn't so they were displaying
inconsistently. Also included labels for questions that didn't have them
> Standardise margin on headers

- app/views/reference-number.html
- app/views/start.html
Had a couple of issues and got in a mess, with git. This fixes the problem though.
> 331 bug mps trn page not loading

- app/views/start.html
As we alternate work on the two journeys it is easy for the copy to get
inconsistent. This applies an update our content designer suggested
for TSLR and applies it to MPS.
> Update start text to be consistent with TSLR

- app/views/repaying-loan.html
Re-word the student loan question so that its clearer for users.
> Change the student loan question

- app/views/multiple-courses-start.html
- app/views/number-of-courses.html
In the journey we currently ask about higher education courses and degree courses. We should consistently ask about degree courses so the maths & physics and student loan journeys are as identical as possible.
> Student loan plan text amends

- app/views/contact.html
- app/views/layout.html
Create contact us page with service specific email. Add in footer link
so users can navigate there.
> Add in contact us page

- app/views/capability.html
- app/views/check-answers.html
- app/views/eligible-confirmed.html
- app/views/index.html
- app/views/ineligible-agency.html
- app/views/ineligible-awarded.html
- app/views/ineligible-capability.html
- app/views/ineligible-degree.html
- app/views/ineligible-disciplinary.html
- app/views/ineligible-school.html
- app/views/ineligible-subject.html
- app/views/ineligible-term.html
- app/views/information-provided.html
- app/views/national-insurance-number.html
- app/views/payment-method.html
- app/views/qualified-alt-1.html
- app/views/qualified-alt-2.html
- app/views/qualified.html
- app/views/reference-number.html
- app/views/repaying-loan.html
- app/views/school.html
- app/views/start.html
- app/views/subject-alt-1.html
- app/views/subject-alt-2.html
- app/views/subject.html
- app/views/supply-teacher-term-alt-1.html
- app/views/supply-teacher-term.html
- app/views/verified.html
Applying changes recommended by content designer for testing
Updated ineligible screens
Updated start page content
Added alternate versions of subject question
Updated school employed question
Updated supply teacher screens
Update information provided page
Added alternate qualified page versions
> Content designer changes

- app/routes.js
Users at ineligible schools were getting confused that they were let
through. We can now specify an array of ineligible schools, so we can
show them the ineligible school screen.
> Prototype checks array of ineligible schools
